export interface Coin {
  id: string;
  symbol: string;
  name: string;
  pair: string;
  price: number;
  priceDecimals: number;
  tickSize: number;
  sizeCeiling: number;
  changePercent: number;
  accent: string;
}

export const coins: Coin[] = [
  {
    id: 'btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    pair: 'BTC/USDT',
    price: 65_774,
    priceDecimals: 2,
    tickSize: 1,
    sizeCeiling: 6,
    changePercent: -0.14,
    accent: '#f7931a',
  },
  {
    id: 'nova',
    symbol: 'NVA',
    name: 'Nova',
    pair: 'NVA/USDT',
    price: 2310.42,
    priceDecimals: 2,
    tickSize: 0.1,
    sizeCeiling: 80,
    changePercent: -1.12,
    accent: '#6c7cff',
  },
  {
    id: 'helix',
    symbol: 'HLX',
    name: 'Helix',
    pair: 'HLX/USDT',
    price: 138.27,
    priceDecimals: 3,
    tickSize: 0.01,
    sizeCeiling: 500,
    changePercent: 5.67,
    accent: '#1fd396',
  },
  {
    id: 'quasar',
    symbol: 'QSR',
    name: 'Quasar',
    pair: 'QSR/USDT',
    price: 0.6321,
    priceDecimals: 4,
    tickSize: 0.0001,
    sizeCeiling: 50_000,
    changePercent: 0.89,
    accent: '#ff5b6a',
  },
  {
    id: 'lumen',
    symbol: 'LMN',
    name: 'Lumen',
    pair: 'LMN/USDT',
    price: 1.0423,
    priceDecimals: 4,
    tickSize: 0.0001,
    sizeCeiling: 40_000,
    changePercent: -0.45,
    accent: '#3aa0ff',
  },
  {
    id: 'apex',
    symbol: 'PEX',
    name: 'Apex',
    pair: 'PEX/USDT',
    price: 7.812,
    priceDecimals: 3,
    tickSize: 0.001,
    sizeCeiling: 9000,
    changePercent: 12.3,
    accent: '#9b6cff',
  },
  {
    id: 'zenith',
    symbol: 'ZEN',
    name: 'Zenith',
    pair: 'ZEN/USDT',
    price: 312.55,
    priceDecimals: 2,
    tickSize: 0.05,
    sizeCeiling: 300,
    changePercent: -3.21,
    accent: '#22d3ee',
  },
  {
    id: 'gilda',
    symbol: 'GLD',
    name: 'Gilda',
    pair: 'GLD/USDT',
    price: 64.18,
    priceDecimals: 3,
    tickSize: 0.01,
    sizeCeiling: 1500,
    changePercent: 1.08,
    accent: '#f0b90b',
  },
  {
    id: 'ionix',
    symbol: 'ION',
    name: 'Ionix',
    pair: 'ION/USDT',
    price: 0.09214,
    priceDecimals: 5,
    tickSize: 0.00001,
    sizeCeiling: 200_000,
    changePercent: 8.42,
    accent: '#ff4fa3',
  },
  {
    id: 'tundra',
    symbol: 'TND',
    name: 'Tundra',
    pair: 'TND/USDT',
    price: 19.305,
    priceDecimals: 3,
    tickSize: 0.005,
    sizeCeiling: 4000,
    changePercent: -0.97,
    accent: '#2dd4bf',
  },
  {
    id: 'verta',
    symbol: 'VRT',
    name: 'Verta',
    pair: 'VRT/USDT',
    price: 5.642,
    priceDecimals: 3,
    tickSize: 0.001,
    sizeCeiling: 11_000,
    changePercent: 3.77,
    accent: '#a3e635',
  },
  {
    id: 'orbex',
    symbol: 'OBX',
    name: 'Orbex',
    pair: 'OBX/USDT',
    price: 0.4187,
    priceDecimals: 4,
    tickSize: 0.0001,
    sizeCeiling: 60_000,
    changePercent: -2.05,
    accent: '#fb7185',
  },
];

export const coinsById: Record<string, Coin> = Object.fromEntries(coins.map((coin) => [coin.id, coin]));
